### ISSUE TITLE
[Feature Request] Custom status message that not `status-online.json` nor `status-offline.json`

### ISSUE THREAD

**Issue by cupangafk** [BlueDevelopersInc/DiscordSRVUtils#147]
**Is your feature request related to a problem? Please describe.**
_

**Describe the solution you'd like**
a custom `messages.json` that got refreshed every `n` times just like `status-online.json` and `status-offline.json`
this custom message can be setup through discord slash command like `/status`

**Describe alternatives you've considered**
_

**Additional context**
- useful for leaderboard on discord
- idk how to make the issue title (feel free to change that)

**Comment by BlueTree242** [comment]
> **Is your feature request related to a problem? Please describe.** _
> 
> **Describe the solution you'd like** a custom `messages.json` that got refreshed every `n` times just like `status-online.json` and `status-offline.json` this custom message can be setup through discord slash command like `/status`
> 
> **Describe alternatives you've considered** _
> 
> **Additional context**
> 
> * useful for leaderboard on discord
> * idk how to make the issue title (feel free to change that)

you mean multiple status messages basically? that was suggested before tho

**Comment by cupangafk** [comment]
> you mean multiple status messages basically? that was suggested before tho

yes

I can't seem to find any issues related to the suggestion you mentioned
sorry if this is a duplicate

> This is a nice feature. However might have to keep discord rate limits in mind if this gets implemented.

true, that is why i wrote 
"refreshed every `n` times just like `status-online.json` and `status-offline.json`"
because we can set those update delay in `status.yml`

which mine was like this
```yaml
# Events to update the status message on.
update_events:
  - 'org.bukkit.event.player.PlayerJoinEvent'
  - 'org.bukkit.event.player.PlayerQuitEvent'
# Delay to update the status message in seconds. Keep in mind discord has rate limits
update_delay: 300 # 5 minutes
```
